# Generated by Django 5.0.4 on 2024-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Portfolio_Website',
            },
        ),
    ]
